### ISSUE TITLE
Can you give an example how to generate the trajectory and then generate the motion? 

### ISSUE THREAD

**Issue by yhw-yhw** [korrawe/guided-motion-diffusion#1]

**Comment by korrawe** [comment]
Hi,
The example for [generating motion from key frames](https://github.com/korrawe/guided-motion-diffusion#generate-from-a-single-prompt---condition-on-keyframe-locations) is doing just that. We first [generate the trajectory](https://github.com/korrawe/guided-motion-diffusion#generate-from-a-single-prompt---condition-on-keyframe-locations) and then use that trajectory to[ generate motion](https://github.com/korrawe/guided-motion-diffusion/blob/main/sample/generate.py#L462) using the second model.

The generated trajectories are also logged in the target directory. You can visualize the output of the trajectory model [here](https://github.com/korrawe/guided-motion-diffusion/blob/main/sample/generate.py#L441).

Best
