### ISSUE TITLE
missing `train_keypoint_mask` in eval

### ISSUE THREAD

**Issue by GuyTevet** [korrawe/guided-motion-diffusion#10]
Hi @korrawe !
Similarly to #2 , [when running eval ](https://github.com/korrawe/guided-motion-diffusion#text-to-motion---with-keyframe-locations-conditioning), I get:

```
Traceback (most recent call last):
  File "/disk1/guytevet/guided-motion-diffusion/eval/eval_humanml_condition.py", line 445, in <module>
    if args.train_keypoint_mask != "none":
AttributeError: 'Namespace' object has no attribute 'train_keypoint_mask'
```

What should be the fix in that case?

Thanks,
Guy

**Comment by korrawe** [comment]
Hi Guy, thanks for bringing this up, you can pull the fix now.
It seems I forgot to remove the `'train_keypoint_mask'` flag in many places. It is not used so you can safely remove them or set them to `"none"`. 

Best

**Comment by GuyTevet** [comment]
Thanks! Closing...
