### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'train_keypoint_mask'

### ISSUE THREAD

**Issue by rykawamura** [korrawe/guided-motion-diffusion#2]
Hi,

I'm currently facing an issue while attempting to test "Motion Synthesis". When I run the command:
`python -m sample.generate --model_path ./save/unet_adazero_xl_x0_abs_proj10_fp16_clipwd_224/model000500000.pt --text_prompt "a person is walking while raising both hands" --guidance_mode kps`
I encounter the following error:
File "/home/user/guided-motion-diffusion/utils/model_util.py", line 110, in get_model_args
    'train_keypoint_mask': args.train_keypoint_mask,
AttributeError: 'Namespace' object has no attribute 'train_keypoint_mask'

Could you please provide guidance on how to resolve this issue?

**Comment by korrawe** [comment]
Hi,
Thank you for pointing this out. I forgot to remove the 'train_keypoint_mask' flag. You can pull the fix from the latest commit now. Or, you can remove any line with 'train_keypoint_mask' from the "./guided-motion-diffusion/utils/model_util.py"
Best,
