### ISSUE TITLE
Is denoiser used in the keyframe location conditioning?

### ISSUE THREAD

**Issue by haosome6** [korrawe/guided-motion-diffusion#3]
In the paper, dense signal propagation uses a denosier, the existing DPM model, to solve the keyframe location conditioning task. Does the code also follow what the paper does? I can only find a reward model in the conditioning task, but in the README I didn't see where to download a reward model nor the instructions to generate samples with a reward model. Thanks for correcting me if I missed something.

**Comment by korrawe** [comment]
Hi,
First, I just updated the arxiv paper recently so it might be a bit clearer in the new version.
For your questions, the only models we need are the motion DPM and the trajectory DPM, and the code does match the paper.

The reward/goal/objective function is defined as cond_fn [here](https://github.com/korrawe/guided-motion-diffusion/blob/main/sample/condition.py#L286). The idea here is that the "reward" or "guidance" does not have to be a model, it can be any function that gives you the gradient toward the objective.

Currently, the "reward model" in the code is not used.

The instruction in the README is in the "[Text to Motion - With keyframe locations conditioning](https://github.com/korrawe/guided-motion-diffusion/tree/main#generate-from-a-single-prompt---condition-on-keyframe-locations)" under Motion Synthesis (it is a dropdown so you need to click it). You can change the pattern in `sample/keyframe_pattern.py`

Best
