### ISSUE TITLE
Max frames in your paper

### ISSUE THREAD

**Issue by zhao-yiqun** [korrawe/guided-motion-diffusion#7]
Hi Karunratanakul

Thanks for amazing work! I have some parameter questions about your code.

I found that in your args of the provided ckpt the num_frames=60. Did this mean that in your experiments of the paper, the maximum frames is 60? But in your given code,  the default num_frames = 224? (I directly run python -m train.train_trajectory, and in my saved args.json, the num_frams=224) I notice that in this file https://github.com/korrawe/guided-motion-diffusion/blob/d4a38acf4256eac195741533e894a289d7a47c15/utils/parser_util.py#L119C16-L119C16, you set the default num_frames=60, however, by changing this default parameters will not lead to the change in final args. I try other parameters like batch_size in TrainingOptions, The parameter will not lead to the change in final args. Could you please check this? I tried a lot and didn't figure out where the training default values come from. Hope that you can help about this.

Thanks in advance
Bests,
Yiqun

**Comment by korrawe** [comment]
Hi Yiqun,

Thank you for your kind words :)
For your questions, the hyperparameters are set in [configs/card.py](https://github.com/korrawe/guided-motion-diffusion/blob/main/configs/card.py) and [configs/model.py](https://github.com/korrawe/guided-motion-diffusion/blob/main/configs/model.py). They are essentially a predefined set of hyperparameters that you load when you create the `train_args()`, for example `args = train_args(base_cls=card.motion_abs_proj10_unet_adagn_xl)` as in [here](https://github.com/korrawe/guided-motion-diffusion/blob/main/train/train_gmd.py#L21C5-L21C69) (with class inheritance, you can mix and match the hyperparameters easily).

I hope this helps!
Best :)
