### ISSUE TITLE
Can I save the outputs with only skeleton nodes?

### ISSUE THREAD

**Issue by AWangji** [korrawe/guided-motion-diffusion#9]
Hi, thanks for your great work!
But as in your README. It seems that I can only output the mp4 files or obj files. Can we output the skeleton files like bvh formats?
Looking forward to your early reply.

**Comment by korrawe** [comment]
Hi, the skeleton is also saved in 'results.npy' in the same directory ([here](https://github.com/korrawe/guided-motion-diffusion/blob/main/sample/generate.py#L588)). 
The skeleton definition can be found [here](https://github.com/korrawe/guided-motion-diffusion/blob/main/data_loaders/humanml_utils.py#L3).

**Comment by deo651** [comment]
> Hi, the skeleton is also saved in 'results.npy' in the same directory ([here](https://github.com/korrawe/guided-motion-diffusion/blob/main/sample/generate.py#L588)). The skeleton definition can be found [here](https://github.com/korrawe/guided-motion-diffusion/blob/main/data_loaders/humanml_utils.py#L3).

is there more infomation? Do I need to transfer the ".npy" files into the ".bvh" using other models? like : https://github.com/KevinLTT/video2bvh
